import { Case, Metric, ActionRequiredItem } from './types';

export const METRICS: Metric[] = [
  { label: 'Total Live Cases', value: '1,284', trend: '+4.2%', type: 'primary' },
  { label: 'Hearings Today', value: '24', subtext: '3 High Court', type: 'secondary' },
  { label: 'No Progress (60d+)', value: '152', trend: 'Action Needed', type: 'error' },
  { label: 'Disposed This Month', value: '48', trend: 'Target Met', type: 'warning' },
];

export const ACTION_REQUIRED: ActionRequiredItem[] = [
  {
    id: '1',
    cnr: 'MHPU01004523',
    title: 'State Bank vs. Mehta Logistics',
    description: "Opponent absent — push for ex-parte in today's session.",
    severity: 'Urgent',
  },
  {
    id: '2',
    cnr: 'DHC020088912',
    title: 'Rajiv Sharma vs. Global Tech Ltd',
    description: 'Evidence affidavit pending. Final extension ends in 48 hours.',
    severity: 'Warning',
  },
  {
    id: '3',
    cnr: 'KAC050011223',
    title: 'M. K. Developers vs. BMC',
    description: "New status update: Bench changed to Hon'ble Justice Iyer.",
    severity: 'Information',
  },
];
export const INDIAN_STATES = [
  'All States',
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry'
];

export const COURT_TYPES = [
  'All Courts',
  'Supreme Court',
  'High Court',
  'District Court',
  'NCLT'
];

export const PRIORITY_CASES: Case[] = [
  {
    id: '1',
    cnr: 'MHPU01004523',
    lan: 'LAN-8829-X',
    parties: 'SBI vs. Mehta Log.',
    partiesDetail: 'DRT Pune',
    court: 'DRT Pune',
    jurisdiction: 'Civil Jurisdiction',
    stage: 'Arguments',
    dpd: 128,
    nextHearing: '12 Oct 2023',
    lawyer: 'Adv. R. Malhotra',
    status: 'Active',
  },
  {
    id: '2',
    cnr: 'DHC020088912',
    lan: 'LAN-4412-B',
    parties: 'Sharma vs. Global Tech',
    partiesDetail: 'Delhi High Court',
    court: 'Delhi High Court',
    jurisdiction: 'Appellate Jurisdiction',
    stage: 'Evidence',
    dpd: 42,
    nextHearing: '15 Oct 2023',
    lawyer: 'Adv. S. Kulkarni',
    status: 'Active',
  },
  {
    id: '3',
    cnr: 'KAC050011223',
    lan: 'LAN-9001-Z',
    parties: 'Developers vs. BMC',
    partiesDetail: 'District Court K.',
    court: 'Karnataka High Court',
    jurisdiction: 'Original Jurisdiction',
    stage: 'Pleading',
    dpd: 12,
    nextHearing: '20 Oct 2023',
    lawyer: 'Adv. P. Shetty',
    status: 'Active',
  },
  {
    id: '4',
    cnr: 'MHOS01007782',
    lan: 'LAN-3309-M',
    parties: 'Tata Power vs. Reliance',
    partiesDetail: 'Comm. Court Mumbai',
    court: 'Comm. Court Mumbai',
    jurisdiction: 'Admiralty Jurisdiction',
    stage: 'Judgment',
    dpd: 156,
    nextHearing: '22 Oct 2023',
    lawyer: 'Adv. V. Raman',
    status: 'Active',
  },
  {
    id: '5',
    cnr: 'UPBN02003314',
    lan: 'LAN-7721-P',
    parties: 'Verma vs. State of UP',
    partiesDetail: 'Allahabad HC',
    court: 'Allahabad HC',
    jurisdiction: 'Civil Jurisdiction',
    stage: 'Stay Vac.',
    dpd: 88,
    nextHearing: '28 Oct 2023',
    lawyer: 'Adv. R. Malhotra',
    status: 'Active',
  },
];
